/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSuggestRouteImport } from './routes/dashboard.suggest'
import { Route as DashboardArchiveRouteImport } from './routes/dashboard.archive'
import { Route as DashboardAddRouteImport } from './routes/dashboard.add'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuggestRoute = DashboardSuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchiveRoute = DashboardArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddRoute = DashboardAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/archive': typeof DashboardArchiveRoute
  '/dashboard/suggest': typeof DashboardSuggestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/archive': typeof DashboardArchiveRoute
  '/dashboard/suggest': typeof DashboardSuggestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/archive': typeof DashboardArchiveRoute
  '/dashboard/suggest': typeof DashboardSuggestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/add'
    | '/dashboard/archive'
    | '/dashboard/suggest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/add'
    | '/dashboard/archive'
    | '/dashboard/suggest'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/add'
    | '/dashboard/archive'
    | '/dashboard/suggest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/suggest': {
      id: '/dashboard/suggest'
      path: '/suggest'
      fullPath: '/dashboard/suggest'
      preLoaderRoute: typeof DashboardSuggestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/archive': {
      id: '/dashboard/archive'
      path: '/archive'
      fullPath: '/dashboard/archive'
      preLoaderRoute: typeof DashboardArchiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/add': {
      id: '/dashboard/add'
      path: '/add'
      fullPath: '/dashboard/add'
      preLoaderRoute: typeof DashboardAddRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAddRoute: typeof DashboardAddRoute
  DashboardArchiveRoute: typeof DashboardArchiveRoute
  DashboardSuggestRoute: typeof DashboardSuggestRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddRoute: DashboardAddRoute,
  DashboardArchiveRoute: DashboardArchiveRoute,
  DashboardSuggestRoute: DashboardSuggestRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
