/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSuggestRouteImport } from './routes/dashboard.suggest'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardArchiveRouteImport } from './routes/dashboard.archive'
import { Route as DashboardAddRouteImport } from './routes/dashboard.add'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DashboardEditItemIdRouteImport } from './routes/dashboard.edit.$itemId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuggestRoute = DashboardSuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchiveRoute = DashboardArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddRoute = DashboardAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEditItemIdRoute = DashboardEditItemIdRouteImport.update({
  id: '/edit/$itemId',
  path: '/edit/$itemId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/archive': typeof DashboardArchiveRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suggest': typeof DashboardSuggestRoute
  '/dashboard/edit/$itemId': typeof DashboardEditItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/archive': typeof DashboardArchiveRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suggest': typeof DashboardSuggestRoute
  '/dashboard/edit/$itemId': typeof DashboardEditItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/archive': typeof DashboardArchiveRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suggest': typeof DashboardSuggestRoute
  '/dashboard/edit/$itemId': typeof DashboardEditItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/mcp'
    | '/dashboard/add'
    | '/dashboard/archive'
    | '/dashboard/audit'
    | '/dashboard/settings'
    | '/dashboard/suggest'
    | '/dashboard/edit/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/mcp'
    | '/dashboard/add'
    | '/dashboard/archive'
    | '/dashboard/audit'
    | '/dashboard/settings'
    | '/dashboard/suggest'
    | '/dashboard/edit/$itemId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/mcp'
    | '/dashboard/add'
    | '/dashboard/archive'
    | '/dashboard/audit'
    | '/dashboard/settings'
    | '/dashboard/suggest'
    | '/dashboard/edit/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/suggest': {
      id: '/dashboard/suggest'
      path: '/suggest'
      fullPath: '/dashboard/suggest'
      preLoaderRoute: typeof DashboardSuggestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/archive': {
      id: '/dashboard/archive'
      path: '/archive'
      fullPath: '/dashboard/archive'
      preLoaderRoute: typeof DashboardArchiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/add': {
      id: '/dashboard/add'
      path: '/add'
      fullPath: '/dashboard/add'
      preLoaderRoute: typeof DashboardAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/edit/$itemId': {
      id: '/dashboard/edit/$itemId'
      path: '/edit/$itemId'
      fullPath: '/dashboard/edit/$itemId'
      preLoaderRoute: typeof DashboardEditItemIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAddRoute: typeof DashboardAddRoute
  DashboardArchiveRoute: typeof DashboardArchiveRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuggestRoute: typeof DashboardSuggestRoute
  DashboardEditItemIdRoute: typeof DashboardEditItemIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddRoute: DashboardAddRoute,
  DashboardArchiveRoute: DashboardArchiveRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuggestRoute: DashboardSuggestRoute,
  DashboardEditItemIdRoute: DashboardEditItemIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
